export const TEXT = {
  shared: {
    restaurants: 'Restaurants',
    chefs: 'Chefs',
    contactUs: 'Contact Us',
    termOfUse: 'Term of Use',
    privacyPolicy: 'Privacy Policy',
  },
  nav: {
    logoAriaLabel: 'Epicure home',
    brandName: 'EPICURE',
    openNavAriaLabel: 'Open navigation',
    searchAriaLabel: 'Search',
    accountAriaLabel: 'Account',
    cartAriaLabel: 'Cart',
  },
  navDrawer: {
    dialogAriaLabel: 'Navigation menu',
    closeAriaLabel: 'Close navigation',
  },
  searchOverlay: {
    dialogAriaLabel: 'Search',
    title: 'Search',
    closeAriaLabel: 'Close search',
    placeholder: 'Search for restaurant, cuisine, chef',
  },
  cart: {
    dialogAriaLabel: 'Shopping cart',
    closeAriaLabel: 'Close cart',
    empty: 'YOUR BAG IS EMPTY',
  },
  signIn: {
    dialogAriaLabel: 'Sign in',
    closeAriaLabel: 'Close sign in',
    closePanelAriaLabel: 'Close sign in panel',
    title: 'SIGN IN',
    subtitle: 'To continue the order, please sign in',
    emailLabel: 'Email address',
    passwordLabel: 'Password',
    loginBtn: 'LOGIN',
    forgotPassword: 'Forget password?',
    divider: 'or',
    signUpBtn: 'SIGN UP',
  },
  footer: {
    navAriaLabel: 'Footer',
  },
  home: {
    heroTitleLine1: 'Good food,',
    heroTitleLine2: 'good mood',
    heroSubtitle: 'Discover the finest restaurants near you',
    heroCta: 'Explore Restaurants',
    mobileHeadline: 'Epicure works with the top chef restaurants in Tel Aviv',
    mobileSearchPlaceholder: 'Search for restaurant cuisine, chef',
    popularTitle: 'POPULAR RESTAURANT IN EPICURE:',
    allRestaurantsLink: 'All Restaurants',
  },
  restaurantDetail: {
    notFound: 'Restaurant not found.',
    openNow: '🕐 Open now',
  },
  restaurantsGrid: {
    tabs: [
      { id: 'all', label: 'All' },
      { id: 'new', label: 'New' },
      { id: 'popular', label: 'Most Popular' },
      { id: 'open', label: 'Open Now' },
      { id: 'map', label: 'Map View' },
    ],
    mapPlaceholder: 'Map view coming soon',
    priceFilter: 'Price Range',
    distanceFilter: 'Distance',
    ratingFilter: 'Rating',
  },
  dishGrid: {
    tabs: ['Breakfast', 'Lunch', 'Dinner'] as const,
  },
} as const;
