export const TEXT = {
  shared: {
    restaurants: 'Restaurants',
    chefs: 'Chefs',
    contactUs: 'Contact Us',
    termOfUse: 'Term of Use',
    privacyPolicy: 'Privacy Policy',
  },
  nav: {
    logoAriaLabel: 'Epicure home',
    brandName: 'EPICURE',
    openNavAriaLabel: 'Open navigation',
    searchAriaLabel: 'Search',
    accountAriaLabel: 'Account',
    cartAriaLabel: 'Cart',
  },
  navDrawer: {
    dialogAriaLabel: 'Navigation menu',
    closeAriaLabel: 'Close navigation',
  },
  searchOverlay: {
    dialogAriaLabel: 'Search',
    title: 'Search',
    closeAriaLabel: 'Close search',
    placeholder: 'Search for restaurant, cuisine, chef',
  },
  cart: {
    dialogAriaLabel: 'Shopping cart',
    closeAriaLabel: 'Close cart',
    empty: 'YOUR BAG IS EMPTY',
    yourOrder: 'YOUR ORDER',
    myOrder: 'MY ORDER',
    total: 'TOTAL',
    checkout: 'CHECKOUT',
    addComment: 'Add A Comment',
    commentPlaceholder: 'Special requests, allergies, dietary restrictions, etc',
    orderHistory: 'ORDER HISTORY',
    deleteItemAriaLabel: 'Remove item from cart',
    decreaseQtyAriaLabel: 'Decrease quantity',
    increaseQtyAriaLabel: 'Increase quantity',
    removeConfirm: 'Remove item?',
    removeYes: 'Yes',
    removeNo: 'Cancel',
    replaceConfirm: 'Replace your current cart with this order?',
  },
  signUp: {
    dialogAriaLabel: 'Sign up',
    closeAriaLabel: 'Close sign up',
    closePanelAriaLabel: 'Close sign up panel',
  },
  signIn: {
    dialogAriaLabel: 'Sign in',
    closeAriaLabel: 'Close sign in',
    closePanelAriaLabel: 'Close sign in panel',
    title: 'SIGN IN',
    signUpTitle: 'SIGN UP',
    subtitle: 'To continue the order, please sign in',
    emailLabel: 'Email address',
    nameLabel: 'Full name',
    passwordLabel: 'Password',
    loginBtn: 'LOGIN',
    forgotPassword: 'Forget password?',
    divider: 'or',
    signUpBtn: 'SIGN UP',
    backToLogin: 'Back to sign in',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  userDropdown: {
    logoutBtn: 'LOG OUT',
    ariaLabel: 'User menu',
  },
  footer: {
    navAriaLabel: 'Footer',
  },
  home: {
    heroTitleLine1: 'Good food,',
    heroTitleLine2: 'good mood',
    heroSubtitle: 'Discover the finest restaurants near you',
    heroCta: 'Explore Restaurants',
    mobileHeadline: 'Epicure works with the top chef restaurants in Tel Aviv',
    mobileSearchPlaceholder: 'Search for restaurant cuisine, chef',
    searchClearAriaLabel: 'Clear search',
    searchResultsRestaurants: 'Restaurants:',
    searchResultsChefs: 'Chefs:',
    searchResultsCuisines: 'Cuisines:',
    popularTitle: 'POPULAR RESTAURANT IN EPICURE:',
    signatureDishTitle: 'SIGNATURE DISH OF:',
    iconsTitle: 'THE MEANING OF OUR ICONS:',
    allRestaurantsLink: 'All Restaurants',
    dishLinkAriaLabel: (name: string) => `View ${name}'s restaurant`,
  },
  icons: [
    { src: '/icons/spicy.svg', label: 'Spicy' },
    { src: '/icons/vegetarian.svg', label: 'Vegetarian' },
    { src: '/icons/vegan.svg', label: 'Vegan' },
  ],
  chefOfTheWeek: {
    sectionTitle: 'CHEF OF THE WEEK:',
    restaurantsLabel: "CHEF'S RESTAURANTS",
    allRestaurantsLink: 'All Restaurants',
    bioPlaceholder: 'Chef bio coming soon.',
    namePlaceholder: 'Chef Name',
  },
  appSection: {
    brandName: 'EPICURE',
    googlePlay: { line1: 'Get it on', line2: 'Google Play' },
    appStore: { line1: 'Download on the', line2: 'App Store' },
    aboutTitle: 'ABOUT US:',
    aboutText: 'At Epicure, we believe that exceptional dining should be both accessible and inspiring. We’ve created a curated marketplace where you can discover new flavors and connect directly with the finest local restaurants, visionary chefs, and their signature dishes. Let us guide you on a journey to find your next culinary obsession, all from the palm of your hand.',
    aboutText2: 'Our intuitive platform and mobile app are designed to make finding the perfect meal effortless. Ready to embark on your next culinary adventure? Download the Epicure app today and let your taste buds lead the way.',
  },
  restaurantDetail: {
    notFound: 'Restaurant not found.',
    openNow: 'Open now',
    opensAt: (time: string) => `Opens at ${time}`,
  },
  dishModal: {
    dialogAriaLabel: 'Dish details',
    closeAriaLabel: 'Close dish details',
    chooseSide: 'Choose a side',
    changes: 'Changes',
    quantity: 'Quantity',
    addToBag: 'ADD TO BAG',
    decreaseAriaLabel: 'Decrease quantity',
    increaseAriaLabel: 'Increase quantity',
  },
  chefModal: {
    dialogAriaLabel: 'Chef details',
    closeAriaLabel: 'Close chef details',
    restaurantsTitle: 'RESTAURANTS',
  },
  deleteOrder: {
    dialogAriaLabel: 'Delete order confirmation',
    icon: '?',
    title: 'DELETE ORDER?',
    message: 'You can order from only one restaurant per order. Going out to another restaurant will erase all the items you put in the cart',
    confirm: 'DELETE',
    confirmAriaLabel: 'Delete current order',
    cancel: 'BACK TO ORDER',
    cancelAriaLabel: 'Go back to order',
  },
  restaurantsGrid: {
    tabs: [
      { id: 'all', label: 'All' },
      { id: 'new', label: 'New' },
      { id: 'popular', label: 'Most Popular' },
      { id: 'open', label: 'Open Now' },
      { id: 'map', label: 'Map View' },
    ],
    mapPlaceholder: 'Map view coming soon',
    priceFilter: 'Price Range',
    distanceFilter: 'Distance',
    distanceMyLocation: 'My location',
    distanceLocationDenied: 'Enable location access in browser settings to use this filter',
    ratingFilter: 'Rating',
    cuisineFilter: 'Cuisine',
    cuisineBannerPrefix: 'Showing:',
    noResults: 'No restaurants match your filters.',
    clearAllFilters: 'Clear all filters',
    clearLabel: 'CLEAR',
  },
  dishGrid: {
    tabs: ['Breakfast', 'Lunch', 'Dinner'] as const,
    openAriaLabel: (dishName: string) => `View ${dishName} details`,
    nodishes: 'No dishes available for this meal time.',
  },
  chefsGrid: {
    tabs: [
      { id: 'all', label: 'All' },
      { id: 'new', label: 'New' },
      { id: 'most-viewed', label: 'Most Viewed' },
    ],
  },
  map: {
    recenterAriaLabel: 'Center map on my location',
  },
  checkout: {
    pageTitle: 'CHECKOUT',
    deliveryDetails: 'DELIVERY DETAILS',
    paymentDetails: 'PAYMENT DETAILS',
    fullName: 'Full Name',
    address: 'Address',
    phone: 'Phone',
    cardNumber: 'Card Number',
    nameOnCard: 'Name On Card',
    cvv: 'CVV',
    expiry: 'Expiry Date',
    expiryPlaceholder: 'MM/YY',
    goBack: 'Go back',
    orderSaved: 'Your order will be saved',
    yourOrder: 'YOUR ORDER',
    addComment: 'Add A Comment',
    commentPlaceholder: 'Special requests, allergies, dietary restrictions, etc.',
    pay: 'PAY',
    submitError: 'Something went wrong placing your order. Please try again.',
    successTitle: 'ORDER RECEIVED',
    successSubtitle: 'Your food is in process',
    arrivingIn: 'Arrives in',
    total: 'TOTAL',
    closeAriaLabel: 'Close',
  },
  cartConflict: {
    title: 'Saved Cart Found',
    message: 'You have items saved from a previous session.',
    question: 'What would you like to do?',
    loadSaved: 'LOAD SAVED CART',
    keepCurrent: 'KEEP CURRENT ITEMS',
  },
  orders: {
    pageTitle: 'YOUR ORDER HISTORY',
    empty: "You haven't placed any orders yet.",
    summaryTitle: 'ORDER SUMMARY',
    orderAgain: 'ORDER AGAIN',
    orderHistory: 'ORDER HISTORY',
    rowAriaLabel: (name: string) => `View order from ${name}`,
    closeAriaLabel: 'Close',
  },
} as const;
