export const TEXT = {
  shared: {
    restaurants: 'Restaurants',
    chefs: 'Chefs',
    contactUs: 'Contact Us',
    termOfUse: 'Term of Use',
    privacyPolicy: 'Privacy Policy',
  },
  nav: {
    logoAriaLabel: 'Epicure home',
    brandName: 'EPICURE',
    openNavAriaLabel: 'Open navigation',
    searchAriaLabel: 'Search',
    accountAriaLabel: 'Account',
    cartAriaLabel: 'Cart',
  },
  navDrawer: {
    dialogAriaLabel: 'Navigation menu',
    closeAriaLabel: 'Close navigation',
  },
  searchOverlay: {
    dialogAriaLabel: 'Search',
    title: 'Search',
    closeAriaLabel: 'Close search',
    placeholder: 'Search for restaurant, cuisine, chef',
  },
  cart: {
    dialogAriaLabel: 'Shopping cart',
    closeAriaLabel: 'Close cart',
    empty: 'YOUR BAG IS EMPTY',
    yourOrder: 'YOUR ORDER',
    myOrder: 'MY ORDER',
    total: 'TOTAL',
    checkout: 'CHECKOUT',
    addComment: 'Add A Comment',
    commentPlaceholder: 'Special requests, allergies, dietary restrictions, etc',
    orderHistory: 'ORDER HISTORY',
  },
  signIn: {
    dialogAriaLabel: 'Sign in',
    closeAriaLabel: 'Close sign in',
    closePanelAriaLabel: 'Close sign in panel',
    title: 'SIGN IN',
    signUpTitle: 'SIGN UP',
    subtitle: 'To continue the order, please sign in',
    emailLabel: 'Email address',
    nameLabel: 'Full name',
    passwordLabel: 'Password',
    loginBtn: 'LOGIN',
    forgotPassword: 'Forget password?',
    divider: 'or',
    signUpBtn: 'SIGN UP',
    backToLogin: 'Back to sign in',
    errorGeneric: 'Something went wrong. Please try again.',
  },
  userDropdown: {
    logoutBtn: 'LOG OUT',
    ariaLabel: 'User menu',
  },
  footer: {
    navAriaLabel: 'Footer',
  },
  home: {
    heroTitleLine1: 'Good food,',
    heroTitleLine2: 'good mood',
    heroSubtitle: 'Discover the finest restaurants near you',
    heroCta: 'Explore Restaurants',
    mobileHeadline: 'Epicure works with the top chef restaurants in Tel Aviv',
    mobileSearchPlaceholder: 'Search for restaurant cuisine, chef',
    searchClearAriaLabel: 'Clear search',
    searchResultsRestaurants: 'Restaurants:',
    searchResultsChefs: 'Chefs:',
    popularTitle: 'POPULAR RESTAURANT IN EPICURE:',
    signatureDishTitle: 'SIGNATURE DISH OF:',
    iconsTitle: 'THE MEANING OF OUR ICONS:',
    allRestaurantsLink: 'All Restaurants',
  },
  icons: [
    { src: '/icons/spicy.svg', label: 'Spicy' },
    { src: '/icons/vegetarian.svg', label: 'Vegetarian' },
    { src: '/icons/vegan.svg', label: 'Vegan' },
  ],
  chefOfTheWeek: {
    sectionTitle: 'CHEF OF THE WEEK:',
    restaurantsLabel: "CHEF'S RESTAURANTS",
    allRestaurantsLink: 'All Restaurants',
    bioPlaceholder: 'Chef bio coming soon.',
    namePlaceholder: 'Chef Name',
  },
  appSection: {
    brandName: 'EPICURE',
    googlePlay: { line1: 'Get it on', line2: 'Google Play' },
    appStore: { line1: 'Download on the', line2: 'App Store' },
    aboutTitle: 'ABOUT US:',
    aboutText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum non eu ipsum. Cras porta malesuada eros, eget blandit turpis suscipit at. Vestibulum sed massa in magna sodales porta. Vivamus elit urna, dignissim a vestibulum.',
    aboutText2: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. In a lacus vel justo fermentum bibendum no eu ipsum. Cras porta malesuada eros.',
  },
  restaurantDetail: {
    notFound: 'Restaurant not found.',
    openNow: 'Open now',
    opensAt: (time: string) => `Opens at ${time}`,
  },
  dishModal: {
    dialogAriaLabel: 'Dish details',
    closeAriaLabel: 'Close dish details',
    chooseSide: 'Choose a side',
    changes: 'Changes',
    quantity: 'Quantity',
    addToBag: 'ADD TO BAG',
    decreaseAriaLabel: 'Decrease quantity',
    increaseAriaLabel: 'Increase quantity',
  },
  deleteOrder: {
    dialogAriaLabel: 'Delete order confirmation',
    icon: '?',
    title: 'DELETE ORDER?',
    message: 'You can order from only one restaurant per order. Going out to another restaurant will erase all the items you put in the cart',
    confirm: 'DELETE',
    confirmAriaLabel: 'Delete current order',
    cancel: 'BACK TO ORDER',
    cancelAriaLabel: 'Go back to order',
  },
  restaurantsGrid: {
    tabs: [
      { id: 'all', label: 'All' },
      { id: 'new', label: 'New' },
      { id: 'popular', label: 'Most Popular' },
      { id: 'open', label: 'Open Now' },
      { id: 'map', label: 'Map View' },
    ],
    mapPlaceholder: 'Map view coming soon',
    priceFilter: 'Price Range',
    distanceFilter: 'Distance',
    distanceMyLocation: 'My location',
    ratingFilter: 'Rating',
  },
  dishGrid: {
    tabs: ['Breakfast', 'Lunch', 'Dinner'] as const,
    openAriaLabel: (dishName: string) => `View ${dishName} details`,
  },
  chefsGrid: {
    tabs: [
      { id: 'all', label: 'All' },
      { id: 'new', label: 'New' },
      { id: 'most-viewed', label: 'Most Viewed' },
    ],
  },
} as const;
