import '../styles/main.scss';
import { TEXT } from '../lib/text';

export const metadata = {
  title: TEXT.nav.brandName,
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
